"""P1: planner LLM-fallback routing, LLM step validation, workflow explanation."""
import pytest

from app.agent.planner import AnalysisPlanner, PlanStep, ExecutionPlan
from app.services.workflow_explainer import explain_plan


class TestLLMFallbackRouting:
    @pytest.mark.asyncio
    async def test_clear_query_uses_rule_plan_even_with_llm_enabled(self, monkeypatch):
        """A query the rule engine understands must not call the LLM."""
        planner = AnalysisPlanner(use_llm=True)
        called = []

        async def fake_llm(query, context=None):
            called.append(query)
            return None

        monkeypatch.setattr(planner, "_llm_plan", fake_llm)
        plan = await planner.plan("compare alpha diversity between groups")
        assert not plan.clarification_needed
        assert called == [], "LLM must not be consulted when the rule plan is specific"

    @pytest.mark.asyncio
    async def test_clarification_query_consults_llm(self, monkeypatch):
        """An unparseable query (clarification_needed) is where the LLM helps."""
        planner = AnalysisPlanner(use_llm=True)

        async def fake_llm(query, context=None):
            return ExecutionPlan(
                query=query,
                steps=[
                    PlanStep(id="step1_validate", module="data_validator"),
                    PlanStep(id="step2_alpha", module="microbiome_alpha",
                             depends_on=["step1_validate"]),
                ],
                estimated_time="~5 min",
                notes=["Generated by LLM planner (kimi-for-coding)"],
            )

        monkeypatch.setattr(planner, "_llm_plan", fake_llm)
        plan = await planner.plan("xyzzy quux frobnicate")
        assert not plan.clarification_needed
        assert any("LLM" in n for n in plan.notes)

    @pytest.mark.asyncio
    async def test_llm_failure_keeps_clarification_plan(self, monkeypatch):
        """LLM unavailable/failing -> the rule clarification plan stands."""
        planner = AnalysisPlanner(use_llm=True)

        async def failing_llm(query, context=None):
            return None

        monkeypatch.setattr(planner, "_llm_plan", failing_llm)
        plan = await planner.plan("xyzzy quux frobnicate")
        assert plan.clarification_needed

    @pytest.mark.asyncio
    async def test_use_llm_false_never_calls_llm(self, monkeypatch):
        planner = AnalysisPlanner(use_llm=False)

        async def boom(query, context=None):
            raise AssertionError("LLM must not be called when use_llm=False")

        monkeypatch.setattr(planner, "_llm_plan", boom)
        plan = await planner.plan("xyzzy quux frobnicate")
        assert plan.clarification_needed


class TestLLMStepValidation:
    def test_unknown_modules_dropped(self):
        steps = AnalysisPlanner._validate_llm_steps([
            {"id": "s1", "module": "data_validator"},
            {"id": "s2", "module": "time_travel_analysis"},   # invented
            {"id": "s3", "module": "microbiome_alpha", "depends_on": ["s1"]},
        ])
        assert [s.module for s in steps] == ["data_validator", "microbiome_alpha"]

    def test_validator_only_plan_rejected(self):
        assert AnalysisPlanner._validate_llm_steps(
            [{"id": "s1", "module": "data_validator"}]) == []

    def test_validator_sorted_first(self):
        steps = AnalysisPlanner._validate_llm_steps([
            {"id": "s1", "module": "microbiome_alpha"},
            {"id": "s2", "module": "data_validator"},
        ])
        assert steps[0].module == "data_validator"

    def test_dangling_dependencies_pruned(self):
        steps = AnalysisPlanner._validate_llm_steps([
            {"id": "s1", "module": "data_validator"},
            {"id": "s2", "module": "microbiome_alpha",
             "depends_on": ["ghost_step"]},
        ])
        assert steps[1].depends_on == []


class TestWorkflowExplainer:
    def test_explains_each_step(self):
        plan = ExecutionPlan(
            query="q",
            steps=[
                PlanStep(id="step1_validate", module="data_validator"),
                PlanStep(id="step2_marker", module="microbiome_marker",
                         params={"transformation": "clr"},
                         depends_on=["step1_validate"]),
            ],
        )
        exp = explain_plan(plan)
        assert exp["n_steps"] == 2
        assert exp["steps"][1]["module"] == "microbiome_marker"
        assert "clr" in exp["steps"][1]["parameters"]
        assert exp["steps"][1]["runs_after"] == ["step1_validate"]
        assert exp["overview"]

    def test_clarification_plan_gets_guidance(self):
        plan = ExecutionPlan(query="q", steps=[], clarification_needed=True)
        exp = explain_plan(plan)
        assert exp["clarification_needed"] is True
        assert "Rephrase" in exp["overview"]

    def test_accepts_dict_form(self):
        exp = explain_plan({"steps": [{"id": "s1", "module": "data_validator"}]})
        assert exp["n_steps"] == 1


class TestPlanEndpointExplanation:
    def test_plan_endpoint_returns_explanation(self, client):
        resp = client.post("/api/v1/agent/plan", json={
            "query": "compare alpha diversity between groups",
            "explain": True,
        })
        assert resp.status_code == 200, resp.text
        payload = resp.json()
        assert payload["explanation"] is not None
        assert payload["explanation"]["n_steps"] == payload["n_steps"]
        assert payload["clarification_needed"] is False

    def test_plan_endpoint_without_explain_omits_it(self, client):
        resp = client.post("/api/v1/agent/plan", json={
            "query": "compare alpha diversity between groups",
        })
        assert resp.status_code == 200
        assert resp.json()["explanation"] is None

    def test_plan_endpoint_reports_clarification(self, client):
        resp = client.post("/api/v1/agent/plan", json={"query": "xyzzy quux"})
        assert resp.status_code == 200
        assert resp.json()["clarification_needed"] is True


class TestInterpretFullLLMSwitch:
    """use_llm=False must guarantee a deterministic KB-only interpretation."""

    def _payload(self):
        return {
            "results": {
                "permanova": {"result_data": {"pvalue": 0.02, "significant": True}},
            },
            "metadata_summary": {"n_samples": 48, "n_groups": 2},
        }

    def test_use_llm_false_never_enhances(self, client):
        resp = client.post("/api/v1/agent/interpret-full",
                           json={**self._payload(), "use_llm": False})
        assert resp.status_code == 200, resp.text
        assert resp.json()["llm_enhanced"] is False

    def test_default_request_schema_accepts_use_llm(self, client):
        resp = client.post("/api/v1/agent/interpret-full", json=self._payload())
        assert resp.status_code == 200, resp.text
        assert "llm_enhanced" in resp.json()
