"""
Agent Workflow Executor
=======================
Executes analysis plans (DAGs) generated by the Planner.

Features:
- Topological sort for dependency ordering
- Parallel execution of independent steps (asyncio.gather)
- State caching for intermediate results
- Streaming events (SSE) for real-time progress
- Error handling with partial results
- Retry logic for transient failures
"""
import asyncio
import logging
import time
import traceback
from pathlib import Path
from typing import Dict, Any, List, Optional, Callable, AsyncGenerator
from dataclasses import dataclass, field
from collections import defaultdict, deque

import pandas as pd

from app.agent.module_registry import get_module_spec, ModuleSpec
from app.agent.planner import ExecutionPlan, PlanStep
from app.services.normalization import run_normalization
from app.services.outlier_detection import run_outlier_detection
from app.services.batch_correction import run_batch_correction
from app.services.imputation import run_imputation
from app.services.paired_differential_test import run_paired_differential_test
from app.services.ancom_bc import run_ancom_bc
from app.services.permanova_strata import run_permanova_strata
from app.services.rgcca import run_rgcca
from app.services.spiec_easi import run_spiec_easi
from app.services.mefisto import run_mefisto
from app.services.mmvec import run_mmvec
from app.services.spatial_gradient import run_spatial_gradient
from app.services.dmi import run_dmi
from app.services.icc_stability import run_icc_stability

logger = logging.getLogger(__name__)


class DataValidationFailed(RuntimeError):
    """Raised when the data_validator step reports unusable input.

    The plan must not continue on data the validator rejected, so this is
    surfaced as a failed step rather than a warning attached to a success.
    """


# ───────────────────────────────────────────────────────────────
# EVENT TYPES (for SSE streaming)
# ───────────────────────────────────────────────────────────────

@dataclass
class ExecutionEvent:
    """Base class for execution events."""
    event_type: str  # 'plan_accepted', 'step_start', 'step_complete', 'step_error', 'review_request', 'complete'
    step_id: Optional[str] = None
    timestamp: float = field(default_factory=time.time)
    payload: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "event_type": self.event_type,
            "step_id": self.step_id,
            "timestamp": self.timestamp,
            "payload": self.payload,
        }


# ───────────────────────────────────────────────────────────────
# MODULE FUNCTION MAPPING
# ───────────────────────────────────────────────────────────────

# Lazy import to avoid circular dependencies
_MODULE_FUNCTIONS: Dict[str, Callable] = {}


def _get_module_function(module_name: str) -> Callable:
    """Get the actual analysis function for a module."""
    global _MODULE_FUNCTIONS

    if not _MODULE_FUNCTIONS:
        # Initialize mapping - import actual analysis functions
        from app.services.analysis_engine import (
            AnalysisEngine,
            run_pcoa,
            run_nmds,
            run_permanova,
            run_anosim,
            run_random_forest,
            run_heatmap,
        )
        from app.services.aldex2 import run_aldex2_analysis
        from app.services.songbird import run_songbird_analysis
        from app.services.enterotype import run_enterotype_analysis
        from app.services.rarefaction import run_rarefaction
        from app.services.taxonomy_bar import run_taxonomy_bar
        from app.services.mofa import run_mofa_plus
        from app.services.diablo import run_diablo
        from app.services.wgcna import run_wgcna
        from app.services.strain_analyzer import run_strain_profile, parse_strain2bscan_output
        from app.services.upset_plot import run_upset_analysis
        from app.services.metabolomics_analysis import (
            run_metabolomics_pca,
            run_metabolomics_alpha_diversity,
            run_metabolomics_marker_discovery,
        )
        from app.services.cross_omics import run_cross_omics_analysis
        from app.services.correlation_analysis import run_correlation_analysis
        from app.services.network_analysis import run_network_analysis
        from app.services.functional_analysis import run_pathway_analysis
        from app.services.functional_prediction import run_functional_prediction
        from app.services.advanced_dimred import (
            run_tsne,
            run_umap,
            maaslin3_associations,
            plotly_tsne,
            plotly_umap,
            plotly_maaslin_volcano,
        )
        from app.services.hierarchical_clustering import run_hierarchical_clustering
        from app.services.phylogenetic_analysis import run_phylogenetic_analysis
        from app.services.source_tracking import run_source_tracking_analysis
        from app.services.sparse_cca import run_sparse_cca_analysis
        from app.services.rda_analysis import run_rda_analysis
        from app.services.o2pls_analysis import run_o2pls_analysis

        from app.services.normalization import run_normalization

        from app.services.data_validator import DataValidator

        from app.services.data_validator import DataValidator

        def validate_data(df=None, df2=None, metadata_df=None, **kw):
            """Run the real validator (app/services/data_validator.py) over every
            table the session provides.

            ``df``/``df2`` are the microbiome and metabolome feature tables in the
            project's canonical features x samples orientation, so metadata sample
            names are matched against the *columns*.

            Returns ``{"valid": bool, "report": {...}, "errors": [...],
            "warnings": [...]}``.  ``valid=False`` is treated by the executor as a
            failed step -- see WorkflowExecutor._blocking_failure.
            """
            validator = DataValidator()
            report: Dict[str, Any] = {}
            errors: List[str] = []
            warnings: List[str] = []

            def _record(layer: str, res) -> None:
                report[layer] = {
                    "is_valid": bool(res.is_valid),
                    "errors": list(res.errors),
                    "warnings": list(res.warnings),
                    "details": res.details,
                }
                errors.extend(f"{layer}: {m}" for m in res.errors)
                warnings.extend(f"{layer}: {m}" for m in res.warnings)

            tables = [
                (layer, table)
                for layer, table in (("microbiome", df), ("metabolome", df2))
                if table is not None and not table.empty
            ]

            if not tables:
                return {
                    "valid": False,
                    "report": {},
                    "errors": [
                        "session: no feature table could be loaded, so no analysis "
                        "step in this plan can run."
                    ],
                    "warnings": [],
                    "validated": [],
                }

            for layer, table in tables:
                _record(layer, validator.validate_abundance_data(table))

            has_metadata = metadata_df is not None and not metadata_df.empty
            if has_metadata:
                _record("metadata", validator.validate_metadata(metadata_df))
                for layer, table in tables:
                    _record(
                        f"{layer}_vs_metadata",
                        validator.validate_feature_metadata_match(table, metadata_df),
                    )
                group_column = kw.get("group_column")
                if group_column and group_column not in metadata_df.columns:
                    errors.append(
                        f"metadata: grouping column '{group_column}' is not in the "
                        f"metadata (available: {list(metadata_df.columns)[:10]})"
                    )
            else:
                warnings.append(
                    "metadata: no metadata table in this session; grouped tests "
                    "(PERMANOVA, marker discovery) cannot run."
                )

            return {
                "valid": not errors,
                "report": report,
                "errors": errors,
                "warnings": warnings,
                "validated": [layer for layer, _ in tables] + (["metadata"] if has_metadata else []),
            }

        def _run_report_generator(results=None, session_id=None, **kw):
            """Render the completed steps into a real PDF via export_service.

            Honesty contract: this never returns a ``report_path`` for a file that
            does not exist.  A format the backend cannot render, or an absent
            reporting dependency, comes back as ``status="unavailable"`` with the
            reason; a genuine generation failure raises so the step is recorded as
            failed.
            """
            fmt = str(kw.get("format") or "pdf").lower()
            title = kw.get("title", "Multi-omics Analysis Report")
            analyses = list(results or [])

            def _unavailable(reason: str) -> Dict[str, Any]:
                return {
                    "status": "unavailable",
                    "report_path": None,
                    "format": fmt,
                    "reason": reason,
                    "n_analyses": len(analyses),
                }

            if fmt != "pdf":
                return _unavailable(
                    f"Report format '{fmt}' is not implemented; app.services."
                    "export_service only renders PDF."
                )
            if not analyses:
                return _unavailable("No completed analysis steps to report on.")

            try:
                from app.services.export_service import generate_comprehensive_report
            except ImportError as e:  # reportlab / plotly stack not installed
                return _unavailable(f"PDF reporting dependency missing: {e}")

            from app.config import settings

            export_dir = (Path(settings.UPLOAD_DIR) / (session_id or "agent") / "exports").resolve()
            export_dir.mkdir(parents=True, exist_ok=True)
            export_path = export_dir / "agent_report.pdf"

            generate_comprehensive_report(
                session_id=session_id or "agent-session",
                export_path=str(export_path),
                analysis_results=analyses,
            )

            if not export_path.exists() or export_path.stat().st_size == 0:
                raise RuntimeError(
                    f"Report generation completed without writing a file to {export_path}"
                )

            out = {
                "status": "generated",
                "report_path": str(export_path),
                "format": "pdf",
                "title": title,
                "size_bytes": export_path.stat().st_size,
                "n_analyses": len(analyses),
                "modules": [a.get("job_type") for a in analyses],
            }
            if session_id:
                out["report_url"] = (
                    f"/api/v1/sessions/{session_id}/export/download"
                    f"?export_id={export_path.name}"
                )
            return out

        def _run_microbiome_marker(df, metadata_df, **kw):
            """Microbiome marker discovery: CLR + Wilcoxon (Mann-Whitney U).

            Session data is stored features x samples, but metabolomics marker
            discovery expects samples x features.
            """
            params = {
                "group_column": kw.get("group_column", "Visit"),
                "reference_group": kw.get("reference_group", "T4"),
                "transformation": "clr",
                "test_method": "mannwhitney",
                "pvalue_threshold": kw.get("pvalue_threshold", 0.05),
                "fc_threshold": kw.get("fc_threshold", 1.5),
            }
            return run_metabolomics_marker_discovery(df.T, metadata_df, **params)

        def _run_metabolome_marker(df, metadata_df, **kw):
            """Metabolome marker discovery: log1p + Welch t-test.

            Session data is stored features x samples, but metabolomics marker
            discovery expects samples x features.
            """
            params = {
                "group_column": kw.get("group_column", "Visit"),
                "reference_group": kw.get("reference_group", "T4"),
                "transformation": "log1p",
                "test_method": "welch",
                "pvalue_threshold": kw.get("pvalue_threshold", 0.05),
                "fc_threshold": kw.get("fc_threshold", 1.5),
            }
            return run_metabolomics_marker_discovery(df.T, metadata_df, **params)

        def _run_procrustes(df, df2=None, metadata_df=None, **kw):
            params = dict(kw)
            params["analysis_type"] = "procrustes"
            params.setdefault("procrustes_method", "pcoa")
            return run_cross_omics_analysis(df, df2, metadata_df, parameters=params)

        def _run_mantel(df, df2=None, metadata_df=None, **kw):
            params = dict(kw)
            params["analysis_type"] = "mantel"
            params.setdefault("mantel_metric", "braycurtis")
            params.setdefault("mantel_method", "pearson")
            params.setdefault("n_permutations", 999)
            return run_cross_omics_analysis(df, df2, metadata_df, parameters=params)

        def _run_tsne(df, metadata_df=None, **kw):
            """t-SNE wrapper that matches the Agent module contract."""
            n_components = kw.get("n_components", 2)
            perplexity = kw.get("perplexity", 30.0)
            coords = run_tsne(df, n_components=n_components, perplexity=perplexity)
            group_column = kw.get("group_column")
            return {
                "plot_data": plotly_tsne(coords, metadata_df, group_column),
                "embeddings": coords.to_dict(orient="records"),
                "n_components": n_components,
                "perplexity": perplexity,
            }

        def _run_umap(df, metadata_df=None, **kw):
            """UMAP wrapper that matches the Agent module contract."""
            n_components = kw.get("n_components", 2)
            n_neighbors = kw.get("n_neighbors", 15)
            min_dist = kw.get("min_dist", 0.1)
            coords = run_umap(df, n_components=n_components, n_neighbors=n_neighbors, min_dist=min_dist)
            group_column = kw.get("group_column")
            return {
                "plot_data": plotly_umap(coords, metadata_df, group_column),
                "embeddings": coords.to_dict(orient="records"),
                "n_components": n_components,
                "n_neighbors": n_neighbors,
                "min_dist": min_dist,
            }

        def _run_maaslin3(df, metadata_df, **kw):
            """MaAsLin3-style wrapper that matches the Agent module contract."""
            fixed_effects = kw.get("fixed_effects", ["Visit"])
            random_effects = kw.get("random_effects") or None
            min_abundance = kw.get("min_abundance", 0.0)
            min_prevalence = kw.get("min_prevalence", 0.0)
            result_df = maaslin3_associations(
                df,
                metadata_df,
                fixed_effects=fixed_effects,
                random_effects=random_effects,
                min_abundance=min_abundance,
                min_prevalence=min_prevalence,
            )
            return {
                "plot_data": plotly_maaslin_volcano(result_df) if not result_df.empty else None,
                "data": result_df.to_dict(orient="records"),
                "n_significant": int((result_df["padj"] < 0.05).sum()) if not result_df.empty else 0,
                "fixed_effects": fixed_effects,
            }

        def _run_volcano(df, metadata_df, **kw):
            """Volcano plot view over microbiome marker discovery.

            A volcano plot is a visualisation of a differential test, so this
            runs the CLR + Wilcoxon marker discovery and surfaces its volcano
            figure as the primary output.
            """
            result = _run_microbiome_marker(df, metadata_df, **kw)
            if isinstance(result, dict):
                plot = result.get("volcano_plot") or result.get("plot_data")
                out = dict(result)
                out["plot_data"] = plot
                return out
            return {"plot_data": None, "error": "marker discovery returned no result"}

        def _run_heatmap(df, metadata_df=None, **kw):
            """Heatmap wrapper: build the Plotly figure from the matrix result.

            analysis_engine.run_heatmap returns the clustered matrix only; the
            agent contract needs a renderable plot_data payload.
            """
            from app.utils.plotly_generator import create_heatmap_plot

            result = run_heatmap(df, metadata_df, parameters={
                "top_n": kw.get("top_n", 50),
                "cluster_rows": kw.get("cluster_rows", True),
                "cluster_cols": kw.get("cluster_cols", True),
                "normalize": kw.get("normalize", "zscore"),
                "group_column": kw.get("group_column"),
            })
            if isinstance(result, dict) and result.get("matrix"):
                matrix_df = pd.DataFrame(result["matrix"])
                result["plot_data"] = create_heatmap_plot(
                    matrix_df,
                    row_labels=[str(i) for i in matrix_df.index],
                    col_labels=[str(c) for c in matrix_df.columns],
                    group_metadata=result.get("group_metadata"),
                    title=f"Top {len(matrix_df)} features heatmap",
                )
            return result

        def _run_unifrac(df, metadata_df=None, **kw):
            """UniFrac wrapper: promote the PCoA plot to plot_data."""
            result = run_phylogenetic_analysis(df, metadata_df, parameters={
                "weighted": kw.get("weighted", True),
                "group_column": kw.get("group_column"),
                "n_permutations": kw.get("n_permutations", 999),
                "nmds_components": kw.get("n_components", 2),
            })
            if isinstance(result, dict) and isinstance(result.get("plots"), dict):
                result["plot_data"] = result["plots"].get("unifrac_pcoa")
            return result

        def _run_source_tracking(df, metadata_df=None, **kw):
            """Source tracking wrapper: promote the proportions plot."""
            result = run_source_tracking_analysis(df, metadata_df, parameters={
                "source_column": kw.get("source_column", "source_type"),
                "method": kw.get("method", "nnls"),
                "sink_samples": kw.get("sink_samples", []),
                "source_samples": kw.get("source_samples", []),
            })
            if isinstance(result, dict) and isinstance(result.get("plots"), dict):
                result["plot_data"] = result["plots"].get("source_proportions")
            return result

        def _run_strain_analyzer(df, metadata_df=None, **kw):
            """Strain profile for one species.

            Strain profiling is per-species; when the plan does not name one,
            the wrapper picks the species with the most strain records instead
            of failing - the choice is reported back in the result.
            """
            species = kw.get("species")
            params = {k: v for k, v in kw.items() if k in ("min_ani", "min_coverage")}
            if not species:
                parsed = parse_strain2bscan_output(df)
                species_col = [c for c in parsed.columns if 'species' in c]
                if not species_col:
                    return {
                        "error": "No species column found in the strain table; "
                                 "pass an explicit 'species' parameter.",
                        "plot_data": None,
                    }
                species = str(parsed[species_col[0]].value_counts().idxmax())
            result, strain_count = run_strain_profile(df, species, params)
            result["species_analyzed"] = species
            result["strain_count"] = strain_count
            return result

        # ── Cross-site / cross-omics wrappers (Zhang et al. 2026) ─────────
        def _site_tables(df, metadata_df, kw):
            """Session microbiome table (features x samples) -> per-site
            subject-level samples x features tables."""
            if metadata_df is None:
                raise ValueError("cross-site analysis requires metadata with site/subject columns")
            from app.services.cross_site_omics import subject_site_tables
            return subject_site_tables(
                df.T, metadata_df,
                site_column=kw.get("site_column"),
                subject_column=kw.get("subject_column"),
            )

        def _subject_level(df2, metadata_df, kw):
            """Metabolome table (features x samples) -> subject-level samples x features."""
            from app.services.multisite_analysis import _detect_subject_column
            t = df2.T
            if metadata_df is None:
                return t
            subj = kw.get("subject_column") or _detect_subject_column(metadata_df)
            common = t.index.intersection(metadata_df.index)
            if subj and len(common):
                return t.loc[common].groupby(metadata_df.loc[common, subj]).mean(numeric_only=True)
            return t

        def _run_cross_site_permanova(df, df2=None, metadata_df=None, **kw):
            from app.services.cross_site_omics import cross_site_explained_variance
            if df2 is None:
                raise ValueError("cross_site_permanova needs a target omics (metabolome) table")
            sites = _site_tables(df, metadata_df, kw)
            target = _subject_level(df2, metadata_df, kw)
            return cross_site_explained_variance(
                sites, target,
                p_threshold=kw.get("p_threshold", 0.05),
                n_perm=kw.get("n_permutations", 999),
                max_features_per_site=kw.get("max_features_per_site", 200),
            )

        def _run_cross_omics_gbdt(df, df2=None, metadata_df=None, **kw):
            from app.services.cross_site_omics import cross_omics_gbdt_screen, subject_site_tables
            if df2 is None:
                raise ValueError("cross_omics_gbdt needs a target omics (metabolome) table")
            target = _subject_level(df2, metadata_df, kw)
            # Which site's features to model with; default: all subjects' table
            site = kw.get("site")
            if site and metadata_df is not None:
                sites = subject_site_tables(df.T, metadata_df, kw.get("site_column"),
                                            kw.get("subject_column"))
                feats = sites.get(site)
                if feats is None:
                    raise ValueError(f"site '{site}' not found; available: {list(sites)}")
            else:
                feats = df.T
            common = feats.index.intersection(target.index)
            return cross_omics_gbdt_screen(
                feats.loc[common], target.loc[common],
                method=kw.get("method", "gbdt"),
                r_threshold=kw.get("r_threshold", 0.3),
                p_threshold=kw.get("p_threshold", 0.05),
                n_bootstrap=kw.get("n_bootstrap", 20),
                cv_folds=kw.get("cv_folds", 5),
                n_targets=kw.get("n_targets"),
            )

        def _run_cross_site_network(df, df2=None, metadata_df=None, **kw):
            from app.services.cross_site_omics import cross_site_correlation_network
            if df2 is None:
                raise ValueError("cross_site_network needs a target omics (metabolome) table")
            sites = _site_tables(df, metadata_df, kw)
            target = _subject_level(df2, metadata_df, kw)
            return cross_site_correlation_network(
                sites, target,
                r_threshold=kw.get("r_threshold", 0.3),
                p_threshold=kw.get("p_threshold", 0.05),
                top_hubs=kw.get("top_hubs", 5),
            )

        def _run_cross_site_concordance(df, df2=None, metadata_df=None, **kw):
            from app.services.cross_site_omics import cross_site_concordance
            group_column = kw.get("group_column")
            if not group_column:
                raise ValueError("cross_site_concordance needs params.group_column")
            layers = _site_tables(df, metadata_df, kw)
            if df2 is not None:
                layers["metabolome"] = _subject_level(df2, metadata_df, kw)
            # metadata must be subject-level to match the layer indices
            from app.services.multisite_analysis import _detect_subject_column
            subj = kw.get("subject_column") or _detect_subject_column(metadata_df)
            if subj:
                md = metadata_df.drop_duplicates(subset=[subj]).set_index(subj)
            else:
                md = metadata_df
            return cross_site_concordance(
                layers, md, group_column,
                min_sites=kw.get("min_sites", 2),
                p_threshold=kw.get("p_threshold", 0.05),
            )

        _MODULE_FUNCTIONS = {
            "data_validator": validate_data,
            "microbiome_pcoa": lambda df, metadata_df=None, **kw: run_pcoa(
                df, metadata_df, parameters={
                    "metric": kw.get("distance_metric", "braycurtis"),
                    "group_column": kw.get("group_column"),
                }
            ),
            "microbiome_nmds": lambda df, metadata_df=None, **kw: run_nmds(
                df, metadata_df, parameters={
                    "metric": kw.get("distance_metric", "braycurtis"),
                    "n_components": kw.get("n_components", 2),
                    "group_column": kw.get("group_column"),
                }
            ),
            "metabolome_pca": lambda df, metadata_df=None, **kw: run_metabolomics_pca(
                df.T, metadata_df,
                group_column=kw.get("group_column"),
                n_components=kw.get("n_components", 10),
                transformation=kw.get("transformation", "zscore"),
            ),
            "microbiome_alpha": lambda df, metadata_df=None, **kw: AnalysisEngine().alpha_diversity(
                df,
                metrics=kw.get("metrics", ["shannon", "simpson"]),
            ),
            "metabolome_alpha": lambda df, metadata_df=None, **kw: run_metabolomics_alpha_diversity(
                df.T, metadata_df,
                group_column=kw.get("group_column"),
                metrics=kw.get("metrics", ["richness", "shannon"]),
            ),
            "permanova": lambda df, metadata_df=None, **kw: run_permanova(
                df, metadata_df, parameters={
                    "metric": kw.get("distance_metric", "braycurtis"),
                    "group_column": kw.get("group_column"),
                    "n_permutations": kw.get("n_permutations", 999),
                }
            ),
            "microbiome_marker": _run_microbiome_marker,
            "metabolome_marker": _run_metabolome_marker,
            "procrustes": _run_procrustes,
            "mantel_test": _run_mantel,
            "sparse_cca": lambda df, df2=None, metadata_df=None, **kw: run_sparse_cca_analysis(
                df.T, df2.T if df2 is not None else None, metadata_df, **kw
            ),
            "rda": lambda df, df2=None, metadata_df=None, **kw: run_rda_analysis(
                df.T, df2.T if df2 is not None else None, metadata_df, **kw
            ),
            "o2pls": lambda df, df2=None, metadata_df=None, **kw: run_o2pls_analysis(
                df.T, df2.T if df2 is not None else None, metadata_df, **kw
            ),
            "cross_correlation": lambda df, df2=None, metadata_df=None, **kw: run_correlation_analysis(
                df, metadata_df, parameters={
                    "method": kw.get("method", "spearman"),
                    "target": "feature",
                    "top_n_features": kw.get("top_n_genera", 15),
                }
            ),
            "network_sparcc": lambda df, metadata_df=None, **kw: run_network_analysis(df, metadata_df, **kw),
            "pathway_kegg": lambda df, **kw: run_pathway_analysis(df, parameters=kw),
            "functional_prediction": lambda df, **kw: run_functional_prediction(df, parameters=kw),
            "tsne": _run_tsne,
            "umap": _run_umap,
            "maaslin3": _run_maaslin3,
            "report_generator": _run_report_generator,
            # ── Previously pending modules (see module_registry history) ──────
            # Orientation contract: session tables are features x samples;
            # services documented as samples x features get df.T.
            "anosim": lambda df, metadata_df=None, **kw: run_anosim(
                df, metadata_df, parameters={
                    "metric": kw.get("distance_metric", "braycurtis"),
                    "group_column": kw.get("group_column"),
                    "n_permutations": kw.get("n_permutations", 999),
                }
            ),
            "random_forest": lambda df, metadata_df=None, **kw: run_random_forest(
                df, metadata_df, parameters={
                    "group_column": kw.get("group_column"),
                    "n_estimators": kw.get("n_estimators", 500),
                }
            ),
            "heatmap": _run_heatmap,
            "volcano": _run_volcano,
            "aldex2": lambda df, metadata_df=None, **kw: run_aldex2_analysis(
                df.T, metadata_df,
                group_column=kw.get("group_column"),
                test_method=kw.get("test_method", "welch"),
                effect_threshold=kw.get("effect_threshold", 1.0),
                alpha=kw.get("pvalue_threshold", 0.05),
            ),
            "songbird": lambda df, metadata_df=None, **kw: run_songbird_analysis(
                df.T, metadata_df,
                group_column=kw.get("group_column"),
                epochs=kw.get("epochs", 1000),
                top_n=kw.get("top_n", 50),
            ),
            "enterotype": lambda df, metadata_df=None, **kw: run_enterotype_analysis(
                df.T, metadata_df,
                n_clusters=kw.get("n_clusters", 3),
                distance_metric=kw.get("distance_metric", "jaccard"),
                clustering_method=kw.get("clustering_method", "pam"),
                group_column=kw.get("group_column"),
            ),
            "rarefaction": lambda df, metadata_df=None, **kw: run_rarefaction(
                df.T, metadata_df,
                group_column=kw.get("group_column"),
                metrics=kw.get("metrics"),
                max_depth=kw.get("max_depth"),
                steps=kw.get("steps", 20),
                iterations=kw.get("iterations", 10),
            ),
            "taxonomy_bar": lambda df, metadata_df=None, **kw: run_taxonomy_bar(
                df, metadata_df,
                group_column=kw.get("group_column"),
                tax_level=kw.get("tax_level", "genus"),
                top_n=kw.get("top_n", 15),
            ),
            "mofa": lambda df, df2=None, metadata_df=None, **kw: run_mofa_plus(
                df.T, df2.T if df2 is not None else None, metadata_df,
                n_factors=kw.get("n_factors", 5),
                group_column=kw.get("group_column"),
            ),
            "diablo": lambda df, df2=None, metadata_df=None, **kw: run_diablo(
                df, df2, metadata_df,
                group_column=kw.get("group_column"),
                n_components=kw.get("n_components", 2),
            ),
            "wgcna": lambda df, metadata_df=None, **kw: run_wgcna(
                df, metadata_df,
                power=kw.get("power", 6),
                min_module_size=kw.get("min_module_size", 10),
                merge_cut_height=kw.get("merge_cut_height", 0.25),
            ),
            "source_tracking": _run_source_tracking,
            "unifrac": _run_unifrac,
            "strain_analyzer": _run_strain_analyzer,
            "upset": lambda df, metadata_df=None, **kw: run_upset_analysis(
                df, metadata_df,
                group_column=kw.get("group_column"),
                prevalence_threshold=kw.get("prevalence_threshold", 0.25),
                top_n=kw.get("top_n", 20),
            ),
            # ── Cross-site / cross-omics (Zhang et al. 2026 framework) ──
            "cross_site_permanova": _run_cross_site_permanova,
            "cross_omics_gbdt": _run_cross_omics_gbdt,
            "cross_site_network": _run_cross_site_network,
            "cross_site_concordance": _run_cross_site_concordance,
            # ── Preprocessing ────────────────────────────────────────
            "normalization": lambda df, metadata_df=None, **kw: run_normalization(
                df,
                data_type=kw.get("data_type", "microbiome"),
                method=kw.get("method", "clr"),
                reference_samples=kw.get("reference_samples"),
            ),
            "outlier_detection": lambda df, metadata_df=None, **kw: run_outlier_detection(
                df,
                metadata_df=metadata_df,
                method=kw.get("method", "aitchison"),
                group_column=kw.get("group_column"),
                threshold=kw.get("threshold", 0.05),
            ),
            "batch_correction": lambda df, metadata_df=None, **kw: run_batch_correction(
                df,
                metadata_df=metadata_df,
                batch_column=kw.get("batch_column"),
                biological_covariates=kw.get("biological_covariates"),
                method=kw.get("method", "combat_seq"),
                data_type=kw.get("data_type", "microbiome"),
            ),
            "imputation": lambda df, metadata_df=None, **kw: run_imputation(
                df,
                method=kw.get("method", "knn"),
                missing_threshold=kw.get("missing_threshold", 0.5),
                data_type=kw.get("data_type", "microbiome"),
            ),
            "paired_differential_test": lambda df, metadata_df=None, **kw: run_paired_differential_test(
                df,
                metadata_df=metadata_df,
                group_column=kw.get("group_column"),
                subject_column=kw.get("subject_column"),
                method=kw.get("method", "paired_wilcoxon"),
                transformation=kw.get("transformation", "clr"),
                pvalue_threshold=kw.get("pvalue_threshold", 0.05),
            ),
            "ancom_bc": lambda df, metadata_df=None, **kw: run_ancom_bc(
                df,
                metadata_df=metadata_df,
                group_column=kw.get("group_column"),
                covariates=kw.get("covariates"),
                random_effects=kw.get("random_effects"),
                pvalue_threshold=kw.get("pvalue_threshold", 0.05),
            ),
            "permanova_strata": lambda df, metadata_df=None, **kw: run_permanova_strata(
                df,
                metadata_df=metadata_df,
                group_column=kw.get("group_column"),
                strata_column=kw.get("strata_column"),
                covariates=kw.get("covariates"),
                distance_metric=kw.get("distance_metric", "braycurtis"),
                n_permutations=kw.get("n_permutations", 999),
            ),
            "rgcca": lambda df, metadata_df=None, **kw: run_rgcca(
                blocks=kw.get("blocks"),
                design_matrix=kw.get("design_matrix"),
                sparsity=kw.get("sparsity", True),
                n_components=kw.get("n_components", 2),
            ),
            "spiec_easi": lambda df, metadata_df=None, **kw: run_spiec_easi(
                df,
                method=kw.get("method", "mb"),
                lambda_min_ratio=kw.get("lambda_min_ratio", 0.01),
                nlambda=kw.get("nlambda", 100),
                rep_num=kw.get("rep_num", 20),
            ),
            "mefisto": lambda df, metadata_df=None, **kw: run_mefisto(
                blocks=kw.get("blocks"),
                metadata_df=metadata_df,
                time_column=kw.get("time_column"),
                subject_column=kw.get("subject_column"),
                n_factors=kw.get("n_factors", 5),
                smoothness=kw.get("smoothness", 0.5),
            ),
            "mmvec": lambda df, metadata_df=None, **kw: run_mmvec(
                microbiome_df=kw.get("microbiome_df"),
                metabolome_df=kw.get("metabolome_df"),
                epochs=kw.get("epochs", 1000),
                latent_dim=kw.get("latent_dim", 50),
                learning_rate=kw.get("learning_rate", 0.001),
            ),
            "spatial_gradient": lambda df, metadata_df=None, **kw: run_spatial_gradient(
                df,
                metadata_df=metadata_df,
                site_column=kw.get("site_column"),
                spatial_distance_matrix=kw.get("spatial_distance_matrix"),
                method=kw.get("method", "distance_decay"),
            ),
            "dmi": lambda df, metadata_df=None, **kw: run_dmi(
                df,
                metadata_df=metadata_df,
                subject_column=kw.get("subject_column"),
                time_column=kw.get("time_column"),
                n_bootstrap=kw.get("n_bootstrap", 20),
            ),
            "icc_stability": lambda df, metadata_df=None, **kw: run_icc_stability(
                df,
                metadata_df=metadata_df,
                subject_column=kw.get("subject_column"),
                time_column=kw.get("time_column"),
                transformation=kw.get("transformation", "clr"),
            ),
        }

    return _MODULE_FUNCTIONS.get(module_name)


# ───────────────────────────────────────────────────────────────
# WORKFLOW EXECUTOR
# ───────────────────────────────────────────────────────────────

class WorkflowExecutor:
    """Executes analysis plans with parallelization and streaming."""

    def __init__(self, session_id: Optional[str] = None):
        self.state: Dict[str, Any] = {}  # step_id -> result
        self.session_data: Dict[str, Any] = {}  # microbiome_df, metabolome_df, metadata_df
        self.completed_steps: set = set()
        self.failed_steps: set = set()
        self.session_id: Optional[str] = session_id
        # step_id -> module name / params, so a report can name what produced each
        # result and so completed results keep their plan order.
        self.step_modules: Dict[str, str] = {}
        self.step_params: Dict[str, Dict[str, Any]] = {}
        self.step_order: List[str] = []

    def set_session_data(self, microbiome_df=None, metabolome_df=None, metadata_df=None):
        """Set the input data for the workflow."""
        self.session_data = {
            "microbiome": microbiome_df,
            "metabolome": metabolome_df,
            "metadata": metadata_df,
        }

    def _topological_sort(self, steps: List[PlanStep]) -> List[PlanStep]:
        """Sort steps by dependencies using Kahn's algorithm."""
        # Build adjacency list
        in_degree = {s.id: 0 for s in steps}
        dependents = defaultdict(list)
        step_map = {s.id: s for s in steps}

        for s in steps:
            for dep in s.depends_on:
                if dep in step_map:
                    dependents[dep].append(s.id)
                    in_degree[s.id] += 1

        # Kahn's algorithm
        queue = deque([sid for sid, deg in in_degree.items() if deg == 0])
        sorted_ids = []

        while queue:
            sid = queue.popleft()
            sorted_ids.append(sid)
            for dep_id in dependents[sid]:
                in_degree[dep_id] -= 1
                if in_degree[dep_id] == 0:
                    queue.append(dep_id)

        if len(sorted_ids) != len(steps):
            # Cycle detected - return original order as fallback
            logger.error("Dependency cycle detected in plan!")
            return steps

        return [step_map[sid] for sid in sorted_ids]

    def _get_parallel_batches(self, steps: List[PlanStep]) -> List[List[PlanStep]]:
        """Group steps into parallel batches based on dependencies."""
        batches = []
        completed = set()
        remaining = set(s.id for s in steps)
        step_map = {s.id: s for s in steps}

        while remaining:
            # Find all steps whose dependencies are satisfied
            batch = []
            for sid in list(remaining):
                step = step_map[sid]
                if all(dep in completed for dep in step.depends_on):
                    batch.append(step)

            if not batch:
                logger.error("Cannot resolve dependencies - possible cycle")
                break

            batches.append(batch)
            for step in batch:
                completed.add(step.id)
                remaining.remove(step.id)

        return batches

    async def _execute_step(self, step: PlanStep) -> Dict[str, Any]:
        """Execute a single analysis step."""
        module_fn = _get_module_function(step.module)
        if not module_fn:
            raise ValueError(f"Unknown module: {step.module}")

        spec = get_module_spec(step.module)
        if not spec:
            raise ValueError(f"No spec found for module: {step.module}")

        # Build arguments based on input requirements
        kwargs = dict(step.params)

        # Add data arguments based on module spec
        reqs = spec.input_requirements
        if reqs.get("microbiome") == "required" or reqs.get("microbiome") == "optional":
            if self.session_data.get("microbiome") is not None:
                kwargs["df"] = self.session_data["microbiome"]
                # For integration methods that need second data frame
                if reqs.get("metabolome") == "required":
                    kwargs["df2"] = self.session_data.get("metabolome")

        if reqs.get("metabolome") == "required" and "df" not in kwargs:
            kwargs["df"] = self.session_data.get("metabolome")

        if reqs.get("metadata") in ("required", "optional"):
            kwargs["metadata_df"] = self.session_data.get("metadata")

        if reqs.get("data") == "required":
            # Default to microbiome if available, otherwise metabolome
            if self.session_data.get("microbiome") is not None:
                kwargs["df"] = self.session_data["microbiome"]
            elif self.session_data.get("metabolome") is not None:
                kwargs["df"] = self.session_data["metabolome"]
            if "data_type" in kwargs:
                if kwargs["data_type"] == "metabolome":
                    kwargs["df"] = self.session_data.get("metabolome")
                else:
                    kwargs["df"] = self.session_data.get("microbiome")

        # The validator inspects every table the session has, so hand it both
        # feature tables explicitly instead of relying on the generic df/df2
        # wiring above (which only fills df2 for integration modules).
        if step.module == "data_validator":
            kwargs["df"] = self.session_data.get("microbiome")
            kwargs["df2"] = self.session_data.get("metabolome")
            kwargs["metadata_df"] = self.session_data.get("metadata")

        # Special handling for report_generator
        if step.module == "report_generator":
            kwargs["results"] = self._completed_results_for_report()
            kwargs["session_id"] = self.session_id

        # Execute
        logger.info(f"Executing step {step.id}: {step.module}")
        start_time = time.time()

        # Run in thread pool for CPU-bound analysis
        loop = asyncio.get_event_loop()
        result = await loop.run_in_executor(None, lambda: module_fn(**kwargs))

        elapsed = time.time() - start_time
        logger.info(f"Step {step.id} completed in {elapsed:.2f}s")

        return {
            "result": result,
            "elapsed_time": elapsed,
            "module": step.module,
            "step_id": step.id,
        }

    def _completed_results_for_report(self) -> List[Dict[str, Any]]:
        """Flatten completed step results into the shape export_service expects.

        app.services.export_service.generate_comprehensive_report consumes a list
        of flat dicts keyed by 'test_method'/'job_type' with an optional
        'plot_data'; analysis modules name their figure differently
        (volcano_plot, heatmap), so the first one present is promoted.
        """
        entries: List[Dict[str, Any]] = []
        for sid in self.step_order:
            if sid not in self.completed_steps or sid not in self.state:
                continue
            module = self.step_modules.get(sid, sid)
            entry: Dict[str, Any] = {}
            result = self.state[sid]
            if isinstance(result, dict):
                entry.update(result)
                if not entry.get("plot_data"):
                    for alt in ("volcano_plot", "heatmap", "plot"):
                        if isinstance(result.get(alt), dict):
                            entry["plot_data"] = result[alt]
                            break
            else:
                entry["value"] = result
            # Module identity wins over anything the result carries, so report
            # sections are titled by the step that produced them.
            entry["job_type"] = module
            entry["test_method"] = module
            entry["step_id"] = sid
            entry["parameters"] = self.step_params.get(sid, {})
            entries.append(entry)
        return entries

    @staticmethod
    def _blocking_failure(step: PlanStep, result: Any) -> Optional[str]:
        """Return a message if a module completed but reported unusable data.

        The validator returns a report instead of raising, so the executor is
        what decides that ``valid: False`` means the step failed.
        """
        if step.module != "data_validator" or not isinstance(result, dict):
            return None
        if result.get("valid", True):
            return None
        errors = result.get("errors") or ["data validation reported the input unusable"]
        return "Data validation failed -- " + "; ".join(str(e) for e in errors[:10])

    async def _execute_batch(self, batch: List[PlanStep]) -> List[ExecutionEvent]:
        """Execute a batch of independent steps in parallel."""
        tasks = [self._execute_step_with_events(step) for step in batch]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        events = []
        for step, result in zip(batch, results):
            if isinstance(result, Exception):
                self.failed_steps.add(step.id)
                events.append(ExecutionEvent(
                    event_type="step_error",
                    step_id=step.id,
                    payload={
                        "error": str(result),
                        "traceback": traceback.format_exc(),
                        "module": step.module,
                    },
                ))
            else:
                events.extend(result)

        return events

    async def _execute_step_with_events(self, step: PlanStep) -> List[ExecutionEvent]:
        """Execute a step and return a list of events."""
        events = []

        # execute() records these from the plan; keep them here too so a step run
        # outside execute() (tests, ad-hoc calls) is still attributable.
        self.step_modules.setdefault(step.id, step.module)
        self.step_params.setdefault(step.id, dict(step.params or {}))
        if step.id not in self.step_order:
            self.step_order.append(step.id)

        # Start event
        events.append(ExecutionEvent(
            event_type="step_start",
            step_id=step.id,
            payload={"module": step.module, "description": step.description},
        ))

        try:
            result = await self._execute_step(step)
            # Keep the result even if it turns out to be a rejection report, so
            # the caller can see *why* validation failed.
            self.state[step.id] = result["result"]

            blocking = self._blocking_failure(step, result["result"])
            if blocking:
                raise DataValidationFailed(blocking)

            self.completed_steps.add(step.id)

            # Complete event
            events.append(ExecutionEvent(
                event_type="step_complete",
                step_id=step.id,
                payload={
                    "module": step.module,
                    "elapsed_time": result["elapsed_time"],
                    "has_plot": "plot_data" in str(result["result"]) or "plot" in str(result["result"]).lower(),
                },
            ))

            # Check if review is needed (e.g., p-value borderline)
            if self._needs_human_review(result["result"]):
                events.append(ExecutionEvent(
                    event_type="review_request",
                    step_id=step.id,
                    payload={"reason": "borderline_significance", "result_summary": self._summarize_result(result["result"])},
                ))

        except Exception as e:
            self.failed_steps.add(step.id)
            events.append(ExecutionEvent(
                event_type="step_error",
                step_id=step.id,
                payload={
                    "module": step.module,
                    "error": str(e),
                    "traceback": traceback.format_exc(),
                },
            ))

        return events

    def _needs_human_review(self, result: Any) -> bool:
        """Check if a result needs human review."""
        # Check for borderline p-values
        if isinstance(result, dict):
            stats = result.get("statistics", {})
            if isinstance(stats, dict):
                pval = stats.get("pvalue") or stats.get("p_value") or stats.get("p")
                if pval is not None and 0.04 < pval < 0.06:
                    return True
        return False

    def _summarize_result(self, result: Any) -> Dict[str, Any]:
        """Create a lightweight summary of a result for review prompts."""
        if not isinstance(result, dict):
            return {"type": "unknown"}

        summary = {"type": "analysis_result"}
        if "statistics" in result:
            summary["statistics"] = result["statistics"]
        if "significant_features" in result:
            summary["n_significant"] = len(result["significant_features"])
        return summary

    async def execute(self, plan: ExecutionPlan) -> AsyncGenerator[ExecutionEvent, None]:
        """
        Execute a plan and yield events.

        Yields:
            ExecutionEvent: Progress events (step_start, step_complete, step_error, etc.)
        """
        # Record plan order up front: steps in a batch finish in whatever order
        # asyncio schedules them, and a report whose sections shuffle between
        # runs is not reproducible.
        for step in plan.steps:
            self.step_modules[step.id] = step.module
            self.step_params[step.id] = dict(step.params or {})
            if step.id not in self.step_order:
                self.step_order.append(step.id)

        # Yield plan accepted event
        yield ExecutionEvent(
            event_type="plan_accepted",
            payload={
                "n_steps": len(plan.steps),
                "modules": [s.module for s in plan.steps],
                "estimated_time": plan.estimated_time,
                "notes": plan.notes,
            },
        )

        # Get parallel batches
        batches = self._get_parallel_batches(plan.steps)
        logger.info(f"Executing plan in {len(batches)} parallel batches")

        for batch in batches:
            # Execute batch
            events = await self._execute_batch(batch)
            for event in events:
                yield event

            # Check if all steps in batch failed - abort if so
            if all(e.event_type == "step_error" for e in events if e.event_type in ("step_complete", "step_error")):
                if len(events) > 0:
                    yield ExecutionEvent(
                        event_type="step_error",
                        payload={"error": "All steps in batch failed, aborting workflow"},
                    )
                    break

        # Yield completion
        success_count = len(self.completed_steps)
        fail_count = len(self.failed_steps)

        yield ExecutionEvent(
            event_type="complete",
            payload={
                "total_steps": len(plan.steps),
                "completed": success_count,
                "failed": fail_count,
                "results": {sid: "completed" for sid in self.completed_steps},
                "final_state_keys": list(self.state.keys()),
            },
        )

    def get_result(self, step_id: str) -> Optional[Any]:
        """Get the result of a completed step."""
        return self.state.get(step_id)

    def get_all_results(self) -> Dict[str, Any]:
        """Get all results."""
        return dict(self.state)


# ───────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ───────────────────────────────────────────────────────────────

async def run_agent_workflow(
    plan: ExecutionPlan,
    microbiome_df=None,
    metabolome_df=None,
    metadata_df=None,
    session_id: Optional[str] = None,
) -> AsyncGenerator[ExecutionEvent, None]:
    """
    Convenience function to run a complete agent workflow.

    Usage:
        async for event in run_agent_workflow(plan, mb_df, met_df, meta_df):
            print(event.to_dict())
    """
    executor = WorkflowExecutor(session_id=session_id)
    executor.set_session_data(microbiome_df, metabolome_df, metadata_df)

    async for event in executor.execute(plan):
        yield event
