"""
Agent Workflow Executor
=======================
Executes analysis plans (DAGs) generated by the Planner.

Features:
- Topological sort for dependency ordering
- Parallel execution of independent steps (asyncio.gather)
- State caching for intermediate results
- Streaming events (SSE) for real-time progress
- Error handling with partial results
- Retry logic for transient failures
"""
import asyncio
import logging
import time
import traceback
from typing import Dict, Any, List, Optional, Callable, AsyncGenerator
from dataclasses import dataclass, field
from collections import defaultdict, deque

from app.agent.module_registry import get_module_spec, ModuleSpec
from app.agent.planner import ExecutionPlan, PlanStep

logger = logging.getLogger(__name__)


# ───────────────────────────────────────────────────────────────
# EVENT TYPES (for SSE streaming)
# ───────────────────────────────────────────────────────────────

@dataclass
class ExecutionEvent:
    """Base class for execution events."""
    event_type: str  # 'plan_accepted', 'step_start', 'step_complete', 'step_error', 'review_request', 'complete'
    step_id: Optional[str] = None
    timestamp: float = field(default_factory=time.time)
    payload: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "event_type": self.event_type,
            "step_id": self.step_id,
            "timestamp": self.timestamp,
            "payload": self.payload,
        }


# ───────────────────────────────────────────────────────────────
# MODULE FUNCTION MAPPING
# ───────────────────────────────────────────────────────────────

# Lazy import to avoid circular dependencies
_MODULE_FUNCTIONS: Dict[str, Callable] = {}


def _get_module_function(module_name: str) -> Callable:
    """Get the actual analysis function for a module."""
    global _MODULE_FUNCTIONS

    if not _MODULE_FUNCTIONS:
        # Initialize mapping - import actual analysis functions
        from app.services.analysis_engine import (
            AnalysisEngine,
            run_pcoa,
            run_nmds,
            run_permanova,
        )
        from app.services.metabolomics_analysis import (
            run_metabolomics_pca,
            run_metabolomics_alpha_diversity,
            run_metabolomics_marker_discovery,
        )
        from app.services.cross_omics import run_cross_omics_analysis
        from app.services.correlation_analysis import run_correlation_analysis
        from app.services.network_analysis import run_network_analysis
        from app.services.functional_analysis import run_pathway_analysis
        from app.services.functional_prediction import run_functional_prediction
        from app.services.advanced_dimred import (
            run_tsne,
            run_umap,
            maaslin3_associations,
            plotly_tsne,
            plotly_umap,
            plotly_maaslin_volcano,
        )
        from app.services.hierarchical_clustering import run_hierarchical_clustering
        from app.services.phylogenetic_analysis import run_phylogenetic_analysis
        from app.services.source_tracking import run_source_tracking_analysis
        from app.services.sparse_cca import run_sparse_cca_analysis
        from app.services.rda_analysis import run_rda_analysis
        from app.services.o2pls_analysis import run_o2pls_analysis

        def validate_data(df, metadata_df=None, **kw):
            return {"valid": True, "report": {}}

        def _run_microbiome_marker(df, metadata_df, **kw):
            """Microbiome marker discovery: CLR + Wilcoxon (Mann-Whitney U).

            Session data is stored features x samples, but metabolomics marker
            discovery expects samples x features.
            """
            params = {
                "group_column": kw.get("group_column", "Visit"),
                "reference_group": kw.get("reference_group", "T4"),
                "transformation": "clr",
                "test_method": "mannwhitney",
                "pvalue_threshold": kw.get("pvalue_threshold", 0.05),
                "fc_threshold": kw.get("fc_threshold", 1.5),
            }
            return run_metabolomics_marker_discovery(df.T, metadata_df, **params)

        def _run_metabolome_marker(df, metadata_df, **kw):
            """Metabolome marker discovery: log1p + Welch t-test.

            Session data is stored features x samples, but metabolomics marker
            discovery expects samples x features.
            """
            params = {
                "group_column": kw.get("group_column", "Visit"),
                "reference_group": kw.get("reference_group", "T4"),
                "transformation": "log1p",
                "test_method": "welch",
                "pvalue_threshold": kw.get("pvalue_threshold", 0.05),
                "fc_threshold": kw.get("fc_threshold", 1.5),
            }
            return run_metabolomics_marker_discovery(df.T, metadata_df, **params)

        def _run_procrustes(df, df2=None, metadata_df=None, **kw):
            params = dict(kw)
            params["analysis_type"] = "procrustes"
            params.setdefault("procrustes_method", "pcoa")
            return run_cross_omics_analysis(df, df2, metadata_df, parameters=params)

        def _run_mantel(df, df2=None, metadata_df=None, **kw):
            params = dict(kw)
            params["analysis_type"] = "mantel"
            params.setdefault("mantel_metric", "braycurtis")
            params.setdefault("mantel_method", "pearson")
            params.setdefault("n_permutations", 999)
            return run_cross_omics_analysis(df, df2, metadata_df, parameters=params)

        def _run_tsne(df, metadata_df=None, **kw):
            """t-SNE wrapper that matches the Agent module contract."""
            n_components = kw.get("n_components", 2)
            perplexity = kw.get("perplexity", 30.0)
            coords = run_tsne(df, n_components=n_components, perplexity=perplexity)
            group_column = kw.get("group_column")
            return {
                "plot_data": plotly_tsne(coords, metadata_df, group_column),
                "embeddings": coords.to_dict(orient="records"),
                "n_components": n_components,
                "perplexity": perplexity,
            }

        def _run_umap(df, metadata_df=None, **kw):
            """UMAP wrapper that matches the Agent module contract."""
            n_components = kw.get("n_components", 2)
            n_neighbors = kw.get("n_neighbors", 15)
            min_dist = kw.get("min_dist", 0.1)
            coords = run_umap(df, n_components=n_components, n_neighbors=n_neighbors, min_dist=min_dist)
            group_column = kw.get("group_column")
            return {
                "plot_data": plotly_umap(coords, metadata_df, group_column),
                "embeddings": coords.to_dict(orient="records"),
                "n_components": n_components,
                "n_neighbors": n_neighbors,
                "min_dist": min_dist,
            }

        def _run_maaslin3(df, metadata_df, **kw):
            """MaAsLin3-style wrapper that matches the Agent module contract."""
            fixed_effects = kw.get("fixed_effects", ["Visit"])
            random_effects = kw.get("random_effects") or None
            min_abundance = kw.get("min_abundance", 0.0)
            min_prevalence = kw.get("min_prevalence", 0.0)
            result_df = maaslin3_associations(
                df,
                metadata_df,
                fixed_effects=fixed_effects,
                random_effects=random_effects,
                min_abundance=min_abundance,
                min_prevalence=min_prevalence,
            )
            return {
                "plot_data": plotly_maaslin_volcano(result_df) if not result_df.empty else None,
                "data": result_df.to_dict(orient="records"),
                "n_significant": int((result_df["padj"] < 0.05).sum()) if not result_df.empty else 0,
                "fixed_effects": fixed_effects,
            }

        _MODULE_FUNCTIONS = {
            "data_validator": validate_data,
            "microbiome_pcoa": lambda df, metadata_df=None, **kw: run_pcoa(
                df, metadata_df, parameters={
                    "metric": kw.get("distance_metric", "braycurtis"),
                    "group_column": kw.get("group_column"),
                }
            ),
            "microbiome_nmds": lambda df, metadata_df=None, **kw: run_nmds(
                df, metadata_df, parameters={
                    "metric": kw.get("distance_metric", "braycurtis"),
                    "n_components": kw.get("n_components", 2),
                    "group_column": kw.get("group_column"),
                }
            ),
            "metabolome_pca": lambda df, metadata_df=None, **kw: run_metabolomics_pca(
                df.T, metadata_df,
                group_column=kw.get("group_column"),
                n_components=kw.get("n_components", 10),
                transformation=kw.get("transformation", "zscore"),
            ),
            "microbiome_alpha": lambda df, metadata_df=None, **kw: AnalysisEngine().alpha_diversity(
                df,
                metrics=kw.get("metrics", ["shannon", "simpson"]),
            ),
            "metabolome_alpha": lambda df, metadata_df=None, **kw: run_metabolomics_alpha_diversity(
                df.T, metadata_df,
                group_column=kw.get("group_column"),
                metrics=kw.get("metrics", ["richness", "shannon"]),
            ),
            "permanova": lambda df, metadata_df=None, **kw: run_permanova(
                df, metadata_df, parameters={
                    "metric": kw.get("distance_metric", "braycurtis"),
                    "group_column": kw.get("group_column"),
                    "n_permutations": kw.get("n_permutations", 999),
                }
            ),
            "microbiome_marker": _run_microbiome_marker,
            "metabolome_marker": _run_metabolome_marker,
            "procrustes": _run_procrustes,
            "mantel_test": _run_mantel,
            "sparse_cca": lambda df, df2=None, metadata_df=None, **kw: run_sparse_cca_analysis(
                df.T, df2.T if df2 is not None else None, metadata_df, **kw
            ),
            "rda": lambda df, df2=None, metadata_df=None, **kw: run_rda_analysis(
                df.T, df2.T if df2 is not None else None, metadata_df, **kw
            ),
            "o2pls": lambda df, df2=None, metadata_df=None, **kw: run_o2pls_analysis(
                df.T, df2.T if df2 is not None else None, metadata_df, **kw
            ),
            "cross_correlation": lambda df, df2=None, metadata_df=None, **kw: run_correlation_analysis(
                df, metadata_df, parameters={
                    "method": kw.get("method", "spearman"),
                    "target": "feature",
                    "top_n_features": kw.get("top_n_genera", 15),
                }
            ),
            "network_sparcc": lambda df, metadata_df=None, **kw: run_network_analysis(df, metadata_df, **kw),
            "pathway_kegg": lambda df, **kw: run_pathway_analysis(df, parameters=kw),
            "functional_prediction": lambda df, **kw: run_functional_prediction(df, parameters=kw),
            "tsne": _run_tsne,
            "umap": _run_umap,
            "maaslin3": _run_maaslin3,
            "report_generator": lambda results, **kw: {"report_path": "/tmp/report.pdf", "format": kw.get("format", "pdf")},
        }

    return _MODULE_FUNCTIONS.get(module_name)


# ───────────────────────────────────────────────────────────────
# WORKFLOW EXECUTOR
# ───────────────────────────────────────────────────────────────

class WorkflowExecutor:
    """Executes analysis plans with parallelization and streaming."""

    def __init__(self):
        self.state: Dict[str, Any] = {}  # step_id -> result
        self.session_data: Dict[str, Any] = {}  # microbiome_df, metabolome_df, metadata_df
        self.completed_steps: set = set()
        self.failed_steps: set = set()

    def set_session_data(self, microbiome_df=None, metabolome_df=None, metadata_df=None):
        """Set the input data for the workflow."""
        self.session_data = {
            "microbiome": microbiome_df,
            "metabolome": metabolome_df,
            "metadata": metadata_df,
        }

    def _topological_sort(self, steps: List[PlanStep]) -> List[PlanStep]:
        """Sort steps by dependencies using Kahn's algorithm."""
        # Build adjacency list
        in_degree = {s.id: 0 for s in steps}
        dependents = defaultdict(list)
        step_map = {s.id: s for s in steps}

        for s in steps:
            for dep in s.depends_on:
                if dep in step_map:
                    dependents[dep].append(s.id)
                    in_degree[s.id] += 1

        # Kahn's algorithm
        queue = deque([sid for sid, deg in in_degree.items() if deg == 0])
        sorted_ids = []

        while queue:
            sid = queue.popleft()
            sorted_ids.append(sid)
            for dep_id in dependents[sid]:
                in_degree[dep_id] -= 1
                if in_degree[dep_id] == 0:
                    queue.append(dep_id)

        if len(sorted_ids) != len(steps):
            # Cycle detected - return original order as fallback
            logger.error("Dependency cycle detected in plan!")
            return steps

        return [step_map[sid] for sid in sorted_ids]

    def _get_parallel_batches(self, steps: List[PlanStep]) -> List[List[PlanStep]]:
        """Group steps into parallel batches based on dependencies."""
        batches = []
        completed = set()
        remaining = set(s.id for s in steps)
        step_map = {s.id: s for s in steps}

        while remaining:
            # Find all steps whose dependencies are satisfied
            batch = []
            for sid in list(remaining):
                step = step_map[sid]
                if all(dep in completed for dep in step.depends_on):
                    batch.append(step)

            if not batch:
                logger.error("Cannot resolve dependencies - possible cycle")
                break

            batches.append(batch)
            for step in batch:
                completed.add(step.id)
                remaining.remove(step.id)

        return batches

    async def _execute_step(self, step: PlanStep) -> Dict[str, Any]:
        """Execute a single analysis step."""
        module_fn = _get_module_function(step.module)
        if not module_fn:
            raise ValueError(f"Unknown module: {step.module}")

        spec = get_module_spec(step.module)
        if not spec:
            raise ValueError(f"No spec found for module: {step.module}")

        # Build arguments based on input requirements
        kwargs = dict(step.params)

        # Add data arguments based on module spec
        reqs = spec.input_requirements
        if reqs.get("microbiome") == "required" or reqs.get("microbiome") == "optional":
            if self.session_data.get("microbiome") is not None:
                kwargs["df"] = self.session_data["microbiome"]
                # For integration methods that need second data frame
                if reqs.get("metabolome") == "required":
                    kwargs["df2"] = self.session_data.get("metabolome")

        if reqs.get("metabolome") == "required" and "df" not in kwargs:
            kwargs["df"] = self.session_data.get("metabolome")

        if reqs.get("metadata") in ("required", "optional"):
            kwargs["metadata_df"] = self.session_data.get("metadata")

        if reqs.get("data") == "required":
            # Default to microbiome if available, otherwise metabolome
            if self.session_data.get("microbiome") is not None:
                kwargs["df"] = self.session_data["microbiome"]
            elif self.session_data.get("metabolome") is not None:
                kwargs["df"] = self.session_data["metabolome"]
            if "data_type" in kwargs:
                if kwargs["data_type"] == "metabolome":
                    kwargs["df"] = self.session_data.get("metabolome")
                else:
                    kwargs["df"] = self.session_data.get("microbiome")

        # Special handling for report_generator
        if step.module == "report_generator":
            kwargs["results"] = {sid: self.state[sid] for sid in self.completed_steps if sid in self.state}

        # Execute
        logger.info(f"Executing step {step.id}: {step.module}")
        start_time = time.time()

        # Run in thread pool for CPU-bound analysis
        loop = asyncio.get_event_loop()
        result = await loop.run_in_executor(None, lambda: module_fn(**kwargs))

        elapsed = time.time() - start_time
        logger.info(f"Step {step.id} completed in {elapsed:.2f}s")

        return {
            "result": result,
            "elapsed_time": elapsed,
            "module": step.module,
            "step_id": step.id,
        }

    async def _execute_batch(self, batch: List[PlanStep]) -> List[ExecutionEvent]:
        """Execute a batch of independent steps in parallel."""
        tasks = [self._execute_step_with_events(step) for step in batch]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        events = []
        for step, result in zip(batch, results):
            if isinstance(result, Exception):
                self.failed_steps.add(step.id)
                events.append(ExecutionEvent(
                    event_type="step_error",
                    step_id=step.id,
                    payload={
                        "error": str(result),
                        "traceback": traceback.format_exc(),
                        "module": step.module,
                    },
                ))
            else:
                events.extend(result)

        return events

    async def _execute_step_with_events(self, step: PlanStep) -> List[ExecutionEvent]:
        """Execute a step and return a list of events."""
        events = []

        # Start event
        events.append(ExecutionEvent(
            event_type="step_start",
            step_id=step.id,
            payload={"module": step.module, "description": step.description},
        ))

        try:
            result = await self._execute_step(step)
            self.state[step.id] = result["result"]
            self.completed_steps.add(step.id)

            # Complete event
            events.append(ExecutionEvent(
                event_type="step_complete",
                step_id=step.id,
                payload={
                    "module": step.module,
                    "elapsed_time": result["elapsed_time"],
                    "has_plot": "plot_data" in str(result["result"]) or "plot" in str(result["result"]).lower(),
                },
            ))

            # Check if review is needed (e.g., p-value borderline)
            if self._needs_human_review(result["result"]):
                events.append(ExecutionEvent(
                    event_type="review_request",
                    step_id=step.id,
                    payload={"reason": "borderline_significance", "result_summary": self._summarize_result(result["result"])},
                ))

        except Exception as e:
            self.failed_steps.add(step.id)
            events.append(ExecutionEvent(
                event_type="step_error",
                step_id=step.id,
                payload={"error": str(e), "traceback": traceback.format_exc()},
            ))

        return events

    def _needs_human_review(self, result: Any) -> bool:
        """Check if a result needs human review."""
        # Check for borderline p-values
        if isinstance(result, dict):
            stats = result.get("statistics", {})
            if isinstance(stats, dict):
                pval = stats.get("pvalue") or stats.get("p_value") or stats.get("p")
                if pval is not None and 0.04 < pval < 0.06:
                    return True
        return False

    def _summarize_result(self, result: Any) -> Dict[str, Any]:
        """Create a lightweight summary of a result for review prompts."""
        if not isinstance(result, dict):
            return {"type": "unknown"}

        summary = {"type": "analysis_result"}
        if "statistics" in result:
            summary["statistics"] = result["statistics"]
        if "significant_features" in result:
            summary["n_significant"] = len(result["significant_features"])
        return summary

    async def execute(self, plan: ExecutionPlan) -> AsyncGenerator[ExecutionEvent, None]:
        """
        Execute a plan and yield events.

        Yields:
            ExecutionEvent: Progress events (step_start, step_complete, step_error, etc.)
        """
        # Yield plan accepted event
        yield ExecutionEvent(
            event_type="plan_accepted",
            payload={
                "n_steps": len(plan.steps),
                "modules": [s.module for s in plan.steps],
                "estimated_time": plan.estimated_time,
                "notes": plan.notes,
            },
        )

        # Get parallel batches
        batches = self._get_parallel_batches(plan.steps)
        logger.info(f"Executing plan in {len(batches)} parallel batches")

        for batch in batches:
            # Execute batch
            events = await self._execute_batch(batch)
            for event in events:
                yield event

            # Check if all steps in batch failed - abort if so
            if all(e.event_type == "step_error" for e in events if e.event_type in ("step_complete", "step_error")):
                if len(events) > 0:
                    yield ExecutionEvent(
                        event_type="step_error",
                        payload={"error": "All steps in batch failed, aborting workflow"},
                    )
                    break

        # Yield completion
        success_count = len(self.completed_steps)
        fail_count = len(self.failed_steps)

        yield ExecutionEvent(
            event_type="complete",
            payload={
                "total_steps": len(plan.steps),
                "completed": success_count,
                "failed": fail_count,
                "results": {sid: "completed" for sid in self.completed_steps},
                "final_state_keys": list(self.state.keys()),
            },
        )

    def get_result(self, step_id: str) -> Optional[Any]:
        """Get the result of a completed step."""
        return self.state.get(step_id)

    def get_all_results(self) -> Dict[str, Any]:
        """Get all results."""
        return dict(self.state)


# ───────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ───────────────────────────────────────────────────────────────

async def run_agent_workflow(
    plan: ExecutionPlan,
    microbiome_df=None,
    metabolome_df=None,
    metadata_df=None,
) -> AsyncGenerator[ExecutionEvent, None]:
    """
    Convenience function to run a complete agent workflow.

    Usage:
        async for event in run_agent_workflow(plan, mb_df, met_df, meta_df):
            print(event.to_dict())
    """
    executor = WorkflowExecutor()
    executor.set_session_data(microbiome_df, metabolome_df, metadata_df)

    async for event in executor.execute(plan):
        yield event
